project_name: Samara_Hack
entity: hlibisev

model:
  name: efficient
  n_classes: 3
  path_to_weights: /home/checkpoints/experiments/auf_Nov27_161440/model.pth

data:
  batch_size: 16
  train_path: /dataset/Cropped/train/
  test_path: /dataset/Cropped/test/
  num_workers: 10

checkpoints_dir: ../checkpoints/

metric: val_samara  # for early stopping
device: 0
early_stoping_patience: 5  # 5 ecpoch before finishing early stoping

lr: 3e-5
size_patch: 64
max_epoch: 1000

